# Generated by Django 4.1.7 on 2023-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classe", models.CharField(max_length=200)),
                ("amende", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=200)),
            ],
        ),
    ]
